import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ToastContainer } from "react-toastify";
import "./globals.css";
import "react-toastify/dist/ReactToastify.css";
import AppHeader from "@/components/app.header";
import AppFooter from "@/components/app.footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Blog Nextjs",
  description: "Generated by Lawther Nguyen",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <AppHeader />
        </header>
        {children}
        <footer>
          <AppFooter />
        </footer>
        <ToastContainer />
      </body>
    </html>
  );
}
